### ISSUE TITLE
El nombre del dataclass debe ir en PascalCase y Singular: PrioridadEntity

### ISSUE THREAD

**Issue by JPichardo2003** [Ruth2002Casilla/Prioridades-Android#1]
https://github.com/Ruth2002Casilla/Prioridades-Android/blob/b9369f993a4dcc7715c6cb57b0f6fca6ac03b2b1/app/src/main/java/edu/ucne/composedemo/data/local/entities/prioridadesEntity.kt#L7

**Comment by Ruth2002Casilla** [comment]
He cambiado el nombre de prioridadesEntity por PrioridadEntity
