### ISSUE TITLE
La validación de descripción no deberia estar anidada a la validación de dias

### ISSUE THREAD

**Issue by AlexanderST01** [Ruth2002Casilla/Prioridades-Android#2]
https://github.com/Ruth2002Casilla/Prioridades-Android/blob/b9369f993a4dcc7715c6cb57b0f6fca6ac03b2b1/app/src/main/java/edu/ucne/composedemo/MainActivity.kt#L116

**Comment by Ruth2002Casilla** [comment]
He cambiado la validación
